### ISSUE TITLE
[Rust] Design pattern for multiple scoring methods

### ISSUE THREAD

**Issue by cswiercz** [aws/random-cut-forest-by-aws#206]
Anomaly scoring is just one use of the data sketch offered by RCF. We want to develop some kind of generic framework for easily adding new visitors. There are several components and stages of the process to consider:

* a `Visitor` is applied to each tree, resulting in some output type `T`
* the output across every tree is processed in some way
  * `anomaly_score()` simply averages the results
  * `impute_missing_values()` returns the median result across all trees.
  * `nearest_neighbor()` does something else

Observations from the Java version: `getAnomalyScore()` and `getNearNeighborsInSample()` follow the `traverseForest()` structure pretty well but `imputeMissingValues()` breaks the pattern. Something more general might be a solution? Also, each algorithm is spread out between what's written in `RandomCutForest`, `traverseForest()`, and in the case of nearest neighbors `Neighbor.collector()`. What if we just put all of these instructions into a new type or separate `impl`?

While we can draw some inspiration from the Java implementation, Rust is not an object-oriented language. Trying to verbatim copy an inheritance pattern using traits is not always possible. (See [this article](https://blog.logrocket.com/what-you-cant-do-in-rust-and-what-to-do-instead/).) Finally, macros may make adding some kind of `ScoringAlgorithm` type to the RCF easier.

**Comment by jotok** [comment]
I would say that impute-missing-values does fit the general pattern pretty well. We just use a different aggregation method for the 1-dimensional case versus the higher-dimensional case. Forecasting does break the pattern: it requires data pre-processing steps that are unique to the forecasting algorithm. I don't see an obvious use case where we would want to re-use that logic for something other than forecasting, but it's worth thinking about.

Regarding code for a particular algorithm being split between a visitor definition and aggregation logic, that's a good callout. I could see defining some kind of "algorithm" struct to explicitly associate the visitor factory and aggregation steps, and a new forest-level traversal method that takes an "algorithm" instead of individual components.

**Comment by cswiercz** [comment]
> I don't see an obvious use case where we would want to re-use that logic for something other than forecasting, but it's worth thinking about.

I guess that was my greater point: Java's `traverseTree()` may be trying to reuse logic too much, as evidenced by some of the scoring patterns. What you say about an "algorithm" struct is more or less a container for all of the logic. Sure, we can let the implementer know that `tree.traverse()` will give you a node path along with some other often used tools. (Perhaps in an algorithm `common.rs` sub-module?)

**Comment by jotok** [comment]
I'm not sure I see what you mean by reusing logic too much. Can you give an example, and possibly a proposal for a different calling convention? I agree that a tree method that returns a traversal path as an iterator would be logically equivalent to the recursive implementation we use in Java for most traversals. We also define something called a "multi-visitor", though, and these might be more awkward to implement as iterators. When walking from the root to a leaf, a multi-visitor can choose to split and send a copy of itself down each branch and then combine again to return the final result. This is how imputation (and hence forecasting) is implemented.

At a higher level, between
```
tree.traverse(queryPoint) -> node iterator
```
and
```
tree.traverse(queryPoint, visitor) -> result
```
the second way reflects my mental model for how the algorithm works, but other than that I personally don't see one as being obviously much better than the other. In a hypothetical distributed context with trees spread out between multiple machines, I think it would be cheaper in most cases to send the visitor over the network instead of the nodes, but I don't think we have any users asking us to prioritize distributed workloads.

**Comment by cswiercz** [comment]
> re: reusing logic

I believe I just need to re-adjust my thinking about the existing Java implementation. The contents of `AbstractForestTraversalExecutor` is pretty tight. But I see some of the code written in `RandomCutForest` and my first thought is, "not all algorithms seem to fit this mold". After some thought I realize that the `Executor` logic is just a tool and that, maybe, you're not suppose to try to cram your scoring logic into that framework. (My previous assumption.)

I should understand more about the current state of things before proposing anything different. I've been trying a few things out and realizing that the logical course is, essentially, something like this executor. (i.e. shoulders of giants, respect what came before)

At this point in my thought process, using separate `impl` blocks might solve most of my usability concerns. That is, if you want to implement a new algorithm into the `RandomCutForest` type then a single module can define the visitor and the usage of the visitor in its own `impl` block.

> re:  second way reflects my mental model for how the algorithm works

I spend just a little bit more time thinking about the problem and realized that this is a good way to think about it. I'm going to change the existing `traverse()` to something named `iter()` (an iterator on nodes) and make a new `traverse()` that accepts a visitor. I have something like this written up so far:

```rust
impl<T> Tree<T>
    where T: Float + Sum
{
    pub fn iter<'a>(&'a self, point: &'a Vec<T>) -> NodeTraverser<'a, T> {
        // return a node iterator
    }

    pub fn traverse<'a, U>(&'a self, point: &'a Vec<T>, visitor: &dyn Visitor<T, Output=U>) -> U {
        // apply the visitor to the node iteration. this is pretty much
        // a non-recursive version of Tree.traverseTree in the Java version
    }
}
```

Again, this is me slowly realizing that the Java version gets a lot of things right...

> re: trees spread out between multiple machines

Great point! Visitors are tiny in comparison.

**Comment by jotok** [comment]
I think it's good to question the design decisions we've made on the Java side. As you point out, Rust is built around a different set of abstractions and we can surely come up with something better than a class by class port of the Java code.

I like the idea of a tree method that returns a lazy iterator for a given query path. One issue for the current implementation of `tree_anomaly_score` is that it calls `.collect()` which looks like it realizes the full path. I think that's not ideal, but we can change the iterator implementation (or add a second implementation) that walks the path in the opposite direction. If we can support moving forward and backward along a path, that would be strictly more general than the recursive implementation.

I think it will be more challenging to implement the "multi-visitor" pattern as an iterator, but we could also choose to implement simple traversals as an iterator and leave multi-traversal as a recursive method.

The reason we introduced "executors" in the Java code was because we wanted to support both single-threaded and parallel execution in `RandomCutForest` by setting a flag when the forest is constructed. We thought this approach would encourage users to experiment with the feature more than if we created separate `RandomCutForest` and `ParallelRandomCutForest` classes (which was another approach we discussed). In Java, `RandomCutForest` is effectively a wrapper around a list of trees and executor classes. With the exception of forecasting, the only logic defined in `RandomCutForest` is to set up the visitors and aggregations that are passed to  a `traverseForest` call. We consider the fact that methods like `getAnomalyScore`, `getSimpleDensity`, and `getNearNeighbors` are all just scaffolding around `traverseForest` to be evidence that the core abstraction is good and empowering to users. Of course, we're just exposing the generic map-reduce operators defined by the Java streams library.

**Comment by cswiercz** [comment]
> re: use of `.collect()`

Created #219 to track this.

> re: multi-visitor

Haven't thought about this problem, yet. Let me know if there are any "gotchas" from the Java side I should keep in the front of my mind.

> re: executors and serial/parallel

How high of a priority is parallel execution? I ask because I expect the inclusion of parallel updates, especially w.r.t. point store operations, will be very different from the current serial tools. A lot of changes will need to be made to the code. Not against making these changes, but I just want to get a sense as to how early this kind of structure and design should be introduced.
