### ISSUE TITLE
[Help] Testing AnomalyScore Runner on input stream

### ISSUE THREAD

**Issue by prateekiiest** [aws/random-cut-forest-by-aws#42]
Hi @sudiptoguha @jotok 

I am currently trying to run the AnomalyScore runner using the CLI command. However, I am not able to figure out what is the exact format of the input stream/input file.

https://github.com/aws/random-cut-forest-by-aws/blob/8ea743b79c37b0235c8d5eb738364de1bff0a565/Java/core/src/main/java/com/amazon/randomcutforest/runner/AnomalyScoreRunner.java#L45

Also using through CLI as mentioned here.

https://github.com/aws/random-cut-forest-by-aws/tree/master/Java#build-command-line-cli-usage

An example would thus really help in this regard.

Thanks
Prateek

**Comment by jotok** [comment]
Hi Prateek! You're right, we should add an example to the README. I've created a new issue (#43) specifically for this.

The Runner expects simple field-delimited lines where the default delimiter is a comma. We use `String::split` to split a line in to fields and `Double::parseDouble` to parse each field into a numeric value. This approach is not robust at all and will fail on simple things, like if the program you used to create the delimited file put quotes around the numeric field. This is intentional: the code is primarily intended to provide an example of library usage, and we didn't want to take additional dependencies to support proper file parsing. If your input file doesn't fit this restrictive format, you'll either have to transform your data or else write your own small program to parse records and submit them to a forest.

**Comment by prateekiiest** [comment]
Thanks, @jotok for the issue.
I agree that an outside file format might be needed later on to reformat any input file in the given format.
Currently, I am able to run pass a single column CSV file and it works fine.
